apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cicd-hpa
  namespace: cicd-project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cicd-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
status:
  observedGeneration: 1
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
