name: Build and Upload WAR and Push Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build JAR file
      run: mvn clean package

    - name: Upload JAR file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-jar-file
        path: target/*.jar

  docker:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: my-jar-file

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: cezeike39/docker:cicd-app
  Sonarqube:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Build and Analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      run: mvn sonar:sonar
      
  nexus:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Configure .netrc
        run: |
          cat <<EOF > $HOME/.netrc
          machine your-nexus-server
          login ${{ secrets.NEXUS_USERNAME }}
          password ${{ secrets.NEXUS_PASSWORD }}
          EOF
        env:
          NEXUS_SERVER: http://13.58.7.12:8081/
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      - name: Upload artifacts
        uses: lfit/nexus-upload-action@v1
        with:
          nexus_url: http://13.58.7.12:8081/
          repository: http://13.58.7.12:8081/repository/maven-releases/
          folder: './target' # Replace with the folder containing your artifacts
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      



 

